/**
 * Supabase-compatible database types for FeedItem storage
 * Defines the database schema and helper types for insert/update operations
 */
import { ContentType, FeedItem, SourcePlatform } from '@/types/reviewTypes';

/**
 * Database representation of FeedItem
 * Dates are stored as ISO strings, enums as strings
 */
export interface FeedItemRow {
  id: string;
  external_id: string;
  source_platform: string; // SourcePlatform enum value
  detected_at: string; // ISO date string
  display_title: string;
  display_description: string;
  display_main_image_url: string;
  display_thumbnail_url: string | null;
  display_action_url: string;
  display_content_type: string; // ContentType enum value
  commerce_currency: string | null;
  commerce_current_price: number | null;
  commerce_original_price: number | null;
  commerce_is_on_sale: boolean | null;
  commerce_merchant_name: string | null;
  metrics_rating_score: number | null;
  metrics_review_count: number | null;
  metrics_view_count: number | null;
  metrics_engagement_score: number;
  tags: string[]; // JSON array
  raw_payload: Record<string, unknown> | null; // JSON object
  created_at?: string; // Auto-generated by Supabase
  updated_at?: string; // Auto-generated by Supabase
}

/**
 * Converts FeedItem to database row format
 */
export function feedItemToRow(feedItem: FeedItem): FeedItemRow {
  return {
    id: feedItem.id,
    external_id: feedItem.externalId,
    source_platform: feedItem.sourcePlatform,
    detected_at: feedItem.detectedAt.toISOString(),
    display_title: feedItem.display.title,
    display_description: feedItem.display.description,
    display_main_image_url: feedItem.display.mainImageUrl,
    display_thumbnail_url: feedItem.display.thumbnailUrl || null,
    display_action_url: feedItem.display.actionUrl,
    display_content_type: feedItem.display.contentType,
    commerce_currency: feedItem.commerce?.currency || null,
    commerce_current_price: feedItem.commerce?.currentPrice || null,
    commerce_original_price: feedItem.commerce?.originalPrice || null,
    commerce_is_on_sale: feedItem.commerce?.isOnSale || null,
    commerce_merchant_name: feedItem.commerce?.merchantName || null,
    metrics_rating_score: feedItem.metrics.ratingScore || null,
    metrics_review_count: feedItem.metrics.reviewCount || null,
    metrics_view_count: feedItem.metrics.viewCount || null,
    metrics_engagement_score: feedItem.metrics.engagementScore,
    tags: feedItem.tags,
    raw_payload: feedItem.rawPayload || null,
  };
}

/**
 * Converts database row to FeedItem format
 */
export function rowToFeedItem(row: FeedItemRow): FeedItem {
  return {
    id: row.id,
    externalId: row.external_id,
    sourcePlatform: row.source_platform as SourcePlatform,
    detectedAt: new Date(row.detected_at),
    display: {
      title: row.display_title,
      description: row.display_description,
      mainImageUrl: row.display_main_image_url,
      thumbnailUrl: row.display_thumbnail_url || undefined,
      actionUrl: row.display_action_url,
      contentType: row.display_content_type as ContentType,
    },
    commerce: row.commerce_currency
      ? {
          currency: row.commerce_currency,
          currentPrice: row.commerce_current_price!,
          originalPrice: row.commerce_original_price || undefined,
          isOnSale: row.commerce_is_on_sale || false,
          merchantName: row.commerce_merchant_name!,
        }
      : null,
    metrics: {
      ratingScore: row.metrics_rating_score || undefined,
      reviewCount: row.metrics_review_count || undefined,
      viewCount: row.metrics_view_count || undefined,
      engagementScore: row.metrics_engagement_score,
    },
    tags: row.tags,
    rawPayload: row.raw_payload || undefined,
  };
}

/**
 * Type for inserting a new FeedItem into the database
 */
export type FeedItemInsert = Omit<FeedItemRow, 'created_at' | 'updated_at'>;

/**
 * Type for updating an existing FeedItem in the database
 */
export type FeedItemUpdate = Partial<Omit<FeedItemRow, 'id' | 'created_at'>>;

/**
 * SQL schema for creating the feed_items table in Supabase
 * This is a reference schema - actual migration should be handled by Supabase migrations
 */
export const FEED_ITEMS_TABLE_SCHEMA = `
CREATE TABLE IF NOT EXISTS feed_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  external_id TEXT NOT NULL,
  source_platform TEXT NOT NULL CHECK (source_platform IN ('amazon', 'google', 'tiktok', 'youtube')),
  detected_at TIMESTAMPTZ NOT NULL,
  display_title TEXT NOT NULL,
  display_description TEXT NOT NULL,
  display_main_image_url TEXT NOT NULL,
  display_thumbnail_url TEXT,
  display_action_url TEXT NOT NULL,
  display_content_type TEXT NOT NULL CHECK (display_content_type IN ('physical_product', 'video_review', 'search_trend')),
  commerce_currency TEXT,
  commerce_current_price NUMERIC(10, 2),
  commerce_original_price NUMERIC(10, 2),
  commerce_is_on_sale BOOLEAN,
  commerce_merchant_name TEXT,
  metrics_rating_score NUMERIC(3, 2) CHECK (metrics_rating_score >= 0 AND metrics_rating_score <= 5),
  metrics_review_count INTEGER CHECK (metrics_review_count >= 0),
  metrics_view_count BIGINT CHECK (metrics_view_count >= 0),
  metrics_engagement_score INTEGER NOT NULL CHECK (metrics_engagement_score >= 0),
  tags TEXT[] DEFAULT '{}',
  raw_payload JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_feed_items_source_platform ON feed_items(source_platform);
CREATE INDEX IF NOT EXISTS idx_feed_items_detected_at ON feed_items(detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_feed_items_engagement_score ON feed_items(metrics_engagement_score DESC);
CREATE INDEX IF NOT EXISTS idx_feed_items_tags ON feed_items USING GIN(tags);
`;

